### ISSUE TITLE
Issue in converting Stereo to mono

### ISSUE THREAD

**Issue by jay739** [despoisj/DeepAudioClassification#22]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    createSlicesFromAudio()
  File "C:\genres\songToData.py", line 71, in createSlicesFromAudio
    createSpectrogramsFromAudio()
  File "C:\genres\songToData.py", line 66, in createSpectrogramsFromAudio
    createSpectrogram(filename,newFilename)
  File "C:\genres\songToData.py", line 42, in createSpectrogram
    os.remove("/tmp/{}.mp3".format(newFilename))
FileNotFoundError: [WinError 3] The system cannot find the path specified: "/tmp/b'Reggae'_1.mp3"

I'm getting this weird error that OS cannot remove the redundant mono tracks. I've tried commenting out the code that converts stereo to mono. To my surprise, only the print statements execute, leaving no spectrograms created. Please help with this problem

**Comment by nikkistonge** [comment]
Hey, I know its maybe a bit late and you've moved on but try out some of the changes in my (accidentally pushed) branch, especially the changes on this line: https://github.com/despoisj/DeepAudioClassification/pull/24/files#diff-ad14b717b5f96f497bfb5d8b8e61e40cR31

I was having the same issue in ~Sept 2018 and I can't remember which changes in that branch fixed it but I was able to get it working.

If I remember correctly it was the actual sox command. After a full 12 hours of research I found that I needed to switch `'` with `"` .  I also had some songs with weird characters in their name and I had to take those out (ex. MØ because it would fail at the O char).
